/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package massalud.Vistas.Orden;

import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import massalud.AccesoAdatos.PrestadorData;
import massalud.Entidades.Prestador;

/**
 *
 * @author daniel
 */
public class PanelLIstOrdenes extends javax.swing.JPanel {
    
    private Connection con = null;
    DefaultTableModel modelo= new DefaultTableModel();
    /**
     * Creates new form PanelLIstOrdenes
     */
    public PanelLIstOrdenes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
 public void cabecera(){
    modelo.addColumn("ID");
        modelo.addColumn("Dni");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Domicilio");
        modelo.addColumn("Telefono");
        modelo.addColumn("Especilidad");
        modelo.addColumn("Estado");
        jTable1.setModel(modelo);

}
    
    public void llenarTabla(){
        PrestadorData presD = new PrestadorData();

        for (Prestador afi : presD.listarPrestador()) {
            String Act = "";
            if(afi.isActivo()==true){
                  Act="activo";  
                }else if (afi.isActivo()==false){
                    Act="Inactivo";
                };
            modelo.addRow(new Object[]{
                afi.getIdPrestador(),
                afi.getDni(),
                afi.getNombre(),
                afi.getApellido(),
                afi.getDomicilio(),
                afi.getTelefono(),
                afi.getEspecialidad().getEspecialidad(),
                Act
            });
        }
    }
}
