/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package massalud.Vistas.Prestador;

import massalud.Vistas.Especialidad.PanelEspecialidad;
import java.awt.BorderLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import massalud.Vistas.afiliado.panelPrincipalAfi;


/**
 *
 * @author daniel
 */
public class panelPrincipalPrestador extends javax.swing.JPanel {

    /**
     * Creates new form panelPrincipal
     */
    public panelPrincipalPrestador() {
        initComponents();
        
        panelInternoPrestador pp = new panelInternoPrestador();
        pp.setSize(702,459);
        pp.setLocation(0, 0);

        jpanelPrestadorCentral.removeAll();
        jpanelPrestadorCentral.add(pp,BorderLayout.CENTER);
        jpanelPrestadorCentral.revalidate();
        jpanelPrestadorCentral.repaint();

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jcambiante = new javax.swing.JLabel();
        jlicontodosAfiliado = new javax.swing.JLabel();
        jlIconMAsAfiliado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jpanelPrestadorCentral = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        jcambiante.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jcambiante.setForeground(new java.awt.Color(255, 255, 255));
        jcambiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/massalud/imagenes/user_icon.png"))); // NOI18N
        jcambiante.setText("Prestador");
        jcambiante.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jcambiante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcambianteMouseClicked(evt);
            }
        });

        jlicontodosAfiliado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/massalud/imagenes/todos.png"))); // NOI18N
        jlicontodosAfiliado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlicontodosAfiliado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlicontodosAfiliadoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlicontodosAfiliadoMouseEntered(evt);
            }
        });

        jlIconMAsAfiliado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/massalud/imagenes/aggremas.png"))); // NOI18N
        jlIconMAsAfiliado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlIconMAsAfiliado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlIconMAsAfiliadoMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/massalud/imagenes/aggremas.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Agregar Especialidad");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Listas");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nuevo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jcambiante, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlIconMAsAfiliado)
                        .addGap(58, 58, 58)
                        .addComponent(jlicontodosAfiliado))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(28, 28, 28))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcambiante)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlicontodosAfiliado)
                            .addComponent(jlIconMAsAfiliado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))))
                .addGap(18, 18, 18))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 70));

        jpanelPrestadorCentral.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpanelPrestadorCentralLayout = new javax.swing.GroupLayout(jpanelPrestadorCentral);
        jpanelPrestadorCentral.setLayout(jpanelPrestadorCentralLayout);
        jpanelPrestadorCentralLayout.setHorizontalGroup(
            jpanelPrestadorCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );
        jpanelPrestadorCentralLayout.setVerticalGroup(
            jpanelPrestadorCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        jPanel1.add(jpanelPrestadorCentral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 710, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jcambianteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcambianteMouseClicked
        // TODO add your handling code her

    }//GEN-LAST:event_jcambianteMouseClicked

    private void jlicontodosAfiliadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlicontodosAfiliadoMouseClicked
        // TODO add your handling code here:
        panelListPrestador pp = new panelListPrestador();
        pp.setSize(702,459);
        pp.setLocation(0, 0);

        jpanelPrestadorCentral.removeAll();
        jpanelPrestadorCentral.add(pp,BorderLayout.CENTER);
        jpanelPrestadorCentral.revalidate();
        jpanelPrestadorCentral.repaint();
        jcambiante.setText("Prestador");
    }//GEN-LAST:event_jlicontodosAfiliadoMouseClicked

    private void jlIconMAsAfiliadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlIconMAsAfiliadoMouseClicked
        // TODO add your handling code here:
        panelInternoPrestador pp = new panelInternoPrestador();
        pp.setSize(702,459);
        pp.setLocation(0, 0);

        jpanelPrestadorCentral.removeAll();
        jpanelPrestadorCentral.add(pp,BorderLayout.CENTER);
        jpanelPrestadorCentral.revalidate();
        jpanelPrestadorCentral.repaint();
        
        jcambiante.setText("Prestador");
    }//GEN-LAST:event_jlIconMAsAfiliadoMouseClicked

    private void jlicontodosAfiliadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlicontodosAfiliadoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jlicontodosAfiliadoMouseEntered

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
         PanelEspecialidad pp = new PanelEspecialidad();
        pp.setSize(702,459);
        pp.setLocation(0, 0);

        jpanelPrestadorCentral.removeAll();
        jpanelPrestadorCentral.add(pp,BorderLayout.CENTER);
        jpanelPrestadorCentral.revalidate();
        jpanelPrestadorCentral.repaint();
       jcambiante.setText("Especialidad");
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
      
        
    }//GEN-LAST:event_jLabel1MouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jcambiante;
    private javax.swing.JLabel jlIconMAsAfiliado;
    private javax.swing.JLabel jlicontodosAfiliado;
    private javax.swing.JPanel jpanelPrestadorCentral;
    // End of variables declaration//GEN-END:variables
}
